#!/bin/bash
set -e

# MeshSilo Docker Entrypoint Script
# Handles initialization and configuration from environment variables

# Set Docker environment flag for Logger to detect
export MESHSILO_DOCKER=true

CONFIG_FILE="/var/www/meshsilo/storage/db/config.local.php"

# Create supervisor log directory
mkdir -p /var/log/supervisor

# Ensure writable directories exist and have correct permissions
mkdir -p /var/www/meshsilo/storage/assets /var/www/meshsilo/storage/logs /var/www/meshsilo/storage/db /var/www/meshsilo/storage/cache /var/www/meshsilo/storage/demo-seed
chown -R www-data:www-data /var/www/meshsilo/storage
chmod -R 775 /var/www/meshsilo/storage

# Create all log files if they don't exist (so tail doesn't fail)
LOG_FILES="php-error.log app.log security.log access.log database.log"
for logfile in $LOG_FILES; do
    touch "/var/www/meshsilo/storage/logs/$logfile"
done
chown -R www-data:www-data /var/www/meshsilo/storage/logs/
chmod 664 /var/www/meshsilo/storage/logs/*.log

# Generate config.local.php if it doesn't exist and environment variables are set
# IMPORTANT: This file should ONLY contain database connection settings.
# All other settings are stored in the database.
if [ ! -f "$CONFIG_FILE" ] && [ -n "$MESHSILO_DB_TYPE" ]; then
    echo "Generating database configuration from environment variables..."

    cat > "$CONFIG_FILE" << 'PHPEOF'
<?php
/**
 * MeshSilo Database Configuration - Generated by Docker
 *
 * This file contains ONLY database connection settings.
 * All other settings (site name, OIDC, etc.) are stored in the database.
 * DO NOT add other settings here - they will be ignored.
 */

PHPEOF

    # Database configuration only
    if [ "$MESHSILO_DB_TYPE" = "mysql" ]; then
        cat >> "$CONFIG_FILE" << PHPEOF
// Database Type
define('DB_TYPE', 'mysql');

// MySQL Connection Settings
define('DB_HOST', '${MESHSILO_DB_HOST:-localhost}');
define('DB_NAME', '${MESHSILO_DB_NAME:-meshsilo}');
define('DB_USER', '${MESHSILO_DB_USER:-meshsilo}');
define('DB_PASS', '${MESHSILO_DB_PASS:-}');

// Installation marker
define('INSTALLED', true);
PHPEOF
    else
        cat >> "$CONFIG_FILE" << 'PHPEOF'
// Database Type
define('DB_TYPE', 'sqlite');
define('DB_PATH', __DIR__ . '/meshsilo.db');

// Installation marker
define('INSTALLED', true);
PHPEOF
    fi

    chown www-data:www-data "$CONFIG_FILE"
    chmod 640 "$CONFIG_FILE"

    echo "Database configuration file created at $CONFIG_FILE"
fi

# Export environment variables for PHP to read (for database initialization)
export MESHSILO_SITE_NAME="${MESHSILO_SITE_NAME:-MeshSilo}"
export MESHSILO_SITE_DESCRIPTION="${MESHSILO_SITE_DESCRIPTION:-3D Print File Manager}"
export MESHSILO_SITE_URL="${MESHSILO_SITE_URL:-}"
export MESHSILO_OIDC_ENABLED="${MESHSILO_OIDC_PROVIDER_URL:+1}"
export MESHSILO_OIDC_PROVIDER_URL="${MESHSILO_OIDC_PROVIDER_URL:-}"
export MESHSILO_OIDC_CLIENT_ID="${MESHSILO_OIDC_CLIENT_ID:-}"
export MESHSILO_OIDC_CLIENT_SECRET="${MESHSILO_OIDC_CLIENT_SECRET:-}"
export MESHSILO_OIDC_REDIRECT_URI="${MESHSILO_OIDC_REDIRECT_URI:-}"
export MESHSILO_OIDC_SCOPES="${MESHSILO_OIDC_SCOPES:-openid profile email}"

# If using SQLite and auto-setup is enabled, initialize the database
if [ "$MESHSILO_AUTO_SETUP" = "true" ] && [ -f "$CONFIG_FILE" ]; then
    # Check if database exists
    if [ "$MESHSILO_DB_TYPE" != "mysql" ] && [ ! -f "/var/www/meshsilo/storage/db/meshsilo.db" ]; then
        echo "Auto-setup enabled but database not found."
        echo "Please visit the installation wizard at /install.php to complete setup."
    fi
fi

# Initialize database settings from environment variables
# This runs after the database is available and updates settings from env vars
if [ -f "$CONFIG_FILE" ]; then
    # Wait for database to be ready (for MySQL)
    if [ "$MESHSILO_DB_TYPE" = "mysql" ]; then
        echo "Waiting for MySQL to be ready..."
        for i in $(seq 1 30); do
            if php -r "
                \$dsn = 'mysql:host=${MESHSILO_DB_HOST:-localhost};dbname=${MESHSILO_DB_NAME:-meshsilo}';
                try {
                    new PDO(\$dsn, '${MESHSILO_DB_USER:-meshsilo}', '${MESHSILO_DB_PASS:-}');
                    exit(0);
                } catch (Exception \$e) {
                    exit(1);
                }
            " 2>/dev/null; then
                echo "MySQL is ready."
                break
            fi
            echo "Waiting for MySQL... ($i/30)"
            sleep 2
        done
    fi

    # Initialize settings from environment variables
    if [ -f "/var/www/meshsilo/cli/init-settings.php" ]; then
        echo "Initializing database settings from environment variables..."
        php /var/www/meshsilo/cli/init-settings.php || true
    fi
fi

# Update PHP upload limits from environment if specified
if [ -n "$MESHSILO_MAX_UPLOAD_SIZE" ]; then
    # Convert to MB for PHP config
    UPLOAD_MB=$(($MESHSILO_MAX_UPLOAD_SIZE / 1048576))

    # Update the custom config file to override defaults
    sed -i "s/^upload_max_filesize = .*/upload_max_filesize = ${UPLOAD_MB}M/" /etc/php/8.1/fpm/conf.d/99-meshsilo.ini
    sed -i "s/^post_max_size = .*/post_max_size = ${UPLOAD_MB}M/" /etc/php/8.1/fpm/conf.d/99-meshsilo.ini

    # Update nginx client_max_body_size
    sed -i "s/client_max_body_size .*/client_max_body_size ${UPLOAD_MB}M;/" /etc/nginx/sites-available/default
fi

# Demo mode: run initial reset and enable periodic resets via supervisor
export MESHSILO_DEMO_CRON=false
if [ "$MESHSILO_DEMO_MODE" = "1" ] || [ "$MESHSILO_DEMO_MODE" = "true" ]; then
    echo "Demo mode enabled. Running initial demo reset to populate sample models..."
    su -s /bin/bash www-data -c "php /var/www/meshsilo/cli/demo-reset.php --force" || echo "Warning: Demo reset failed (database may not be initialized yet)"
    export MESHSILO_DEMO_CRON=true
fi

echo "MeshSilo Docker container starting..."
echo "Access the application at http://localhost:80"

# Execute the main command
exec "$@"
