#!/bin/bash
set -e

# Silo Docker Entrypoint Script
# Handles initialization and configuration from environment variables

CONFIG_FILE="/var/www/silo/config.local.php"

# Create supervisor log directory
mkdir -p /var/log/supervisor

# Ensure writable directories exist and have correct permissions
mkdir -p /var/www/silo/assets /var/www/silo/logs /var/www/silo/db
chown -R www-data:www-data /var/www/silo/assets /var/www/silo/logs /var/www/silo/db
chmod -R 775 /var/www/silo/assets /var/www/silo/logs /var/www/silo/db

# Generate config.local.php if it doesn't exist and environment variables are set
if [ ! -f "$CONFIG_FILE" ] && [ -n "$SILO_DB_TYPE" ]; then
    echo "Generating configuration from environment variables..."

    cat > "$CONFIG_FILE" << 'PHPEOF'
<?php
// Silo Configuration - Generated by Docker
// This file is auto-generated. To customize, mount your own config.local.php

PHPEOF

    # Database configuration
    if [ "$SILO_DB_TYPE" = "mysql" ]; then
        cat >> "$CONFIG_FILE" << PHPEOF
// Database Configuration (MySQL)
define('DB_TYPE', 'mysql');
define('DB_HOST', '${SILO_DB_HOST:-localhost}');
define('DB_NAME', '${SILO_DB_NAME:-silo}');
define('DB_USER', '${SILO_DB_USER:-silo}');
define('DB_PASS', '${SILO_DB_PASS:-}');

PHPEOF
    else
        cat >> "$CONFIG_FILE" << 'PHPEOF'
// Database Configuration (SQLite)
define('DB_TYPE', 'sqlite');
define('DB_PATH', __DIR__ . '/db/silo.db');

PHPEOF
    fi

    # Site configuration
    cat >> "$CONFIG_FILE" << PHPEOF
// Site Configuration
define('SITE_NAME', '${SILO_SITE_NAME:-Silo}');
define('SITE_DESCRIPTION', '${SILO_SITE_DESCRIPTION:-3D Print File Manager}');
define('SITE_URL', '${SILO_SITE_URL:-}');

PHPEOF

    # OIDC configuration if enabled
    if [ -n "$SILO_OIDC_PROVIDER_URL" ]; then
        cat >> "$CONFIG_FILE" << PHPEOF
// OIDC Configuration
define('OIDC_ENABLED', true);
define('OIDC_PROVIDER_URL', '${SILO_OIDC_PROVIDER_URL}');
define('OIDC_CLIENT_ID', '${SILO_OIDC_CLIENT_ID:-}');
define('OIDC_CLIENT_SECRET', '${SILO_OIDC_CLIENT_SECRET:-}');
define('OIDC_REDIRECT_URI', '${SILO_OIDC_REDIRECT_URI:-}');
define('OIDC_SCOPES', '${SILO_OIDC_SCOPES:-openid profile email}');
define('OIDC_USERNAME_CLAIM', '${SILO_OIDC_USERNAME_CLAIM:-preferred_username}');
define('OIDC_DISPLAY_NAME_CLAIM', '${SILO_OIDC_DISPLAY_NAME_CLAIM:-name}');
define('OIDC_EMAIL_CLAIM', '${SILO_OIDC_EMAIL_CLAIM:-email}');
define('OIDC_AUTO_REGISTER', ${SILO_OIDC_AUTO_REGISTER:-true});
define('OIDC_DEFAULT_GROUP', '${SILO_OIDC_DEFAULT_GROUP:-}');

PHPEOF
    else
        cat >> "$CONFIG_FILE" << 'PHPEOF'
// OIDC Configuration (disabled)
define('OIDC_ENABLED', false);

PHPEOF
    fi

    # Settings
    cat >> "$CONFIG_FILE" << PHPEOF
// Application Settings
define('ALLOWED_EXTENSIONS', '${SILO_ALLOWED_EXTENSIONS:-stl,3mf}');
define('MAX_UPLOAD_SIZE', '${SILO_MAX_UPLOAD_SIZE:-104857600}');
define('DEDUP_ENABLED', ${SILO_DEDUP_ENABLED:-true});

PHPEOF

    chown www-data:www-data "$CONFIG_FILE"
    chmod 640 "$CONFIG_FILE"

    echo "Configuration file created at $CONFIG_FILE"
fi

# If using SQLite and auto-setup is enabled, initialize the database
if [ "$SILO_AUTO_SETUP" = "true" ] && [ -f "$CONFIG_FILE" ]; then
    # Check if database exists
    if [ "$SILO_DB_TYPE" != "mysql" ] && [ ! -f "/var/www/silo/db/silo.db" ]; then
        echo "Auto-setup enabled but database not found."
        echo "Please visit the installation wizard at /install.php to complete setup."
    fi
fi

# Update PHP upload limits from environment if specified
if [ -n "$SILO_MAX_UPLOAD_SIZE" ]; then
    # Convert to MB for PHP config
    UPLOAD_MB=$(($SILO_MAX_UPLOAD_SIZE / 1048576))
    sed -i "s/upload_max_filesize = .*/upload_max_filesize = ${UPLOAD_MB}M/" /etc/php/8.1/fpm/php.ini
    sed -i "s/post_max_size = .*/post_max_size = ${UPLOAD_MB}M/" /etc/php/8.1/fpm/php.ini

    # Update nginx client_max_body_size
    sed -i "s/client_max_body_size .*/client_max_body_size ${UPLOAD_MB}M;/" /etc/nginx/sites-available/default
fi

echo "Silo Docker container starting..."
echo "Access the application at http://localhost:80"

# Execute the main command
exec "$@"
