#!/bin/bash
set -e

# MeshSilo Docker Entrypoint Script
# Handles initialization and configuration from environment variables

CONFIG_FILE="/var/www/meshsilo/db/config.local.php"

# Create supervisor log directory
mkdir -p /var/log/supervisor

# Ensure writable directories exist and have correct permissions
mkdir -p /var/www/meshsilo/assets /var/www/meshsilo/logs /var/www/meshsilo/db /var/www/meshsilo/cache
chown -R www-data:www-data /var/www/meshsilo/assets /var/www/meshsilo/logs /var/www/meshsilo/db /var/www/meshsilo/cache
chmod -R 775 /var/www/meshsilo/assets /var/www/meshsilo/logs /var/www/meshsilo/db /var/www/meshsilo/cache

# Create PHP error log file if it doesn't exist (so tail doesn't fail)
touch /var/www/meshsilo/logs/php-error.log
chown www-data:www-data /var/www/meshsilo/logs/php-error.log

# Generate config.local.php if it doesn't exist and environment variables are set
if [ ! -f "$CONFIG_FILE" ] && [ -n "$MESHSILO_DB_TYPE" ]; then
    echo "Generating configuration from environment variables..."

    cat > "$CONFIG_FILE" << 'PHPEOF'
<?php
// MeshSilo Configuration - Generated by Docker
// This file is stored in db/config.local.php (persistent volume)
// To customize, mount your own config file to this location

PHPEOF

    # Database configuration
    if [ "$MESHSILO_DB_TYPE" = "mysql" ]; then
        cat >> "$CONFIG_FILE" << PHPEOF
// Database Configuration (MySQL)
define('DB_TYPE', 'mysql');
define('DB_HOST', '${MESHSILO_DB_HOST:-localhost}');
define('DB_NAME', '${MESHSILO_DB_NAME:-meshsilo}');
define('DB_USER', '${MESHSILO_DB_USER:-meshsilo}');
define('DB_PASS', '${MESHSILO_DB_PASS:-}');

PHPEOF
    else
        cat >> "$CONFIG_FILE" << 'PHPEOF'
// Database Configuration (SQLite)
define('DB_TYPE', 'sqlite');
define('DB_PATH', __DIR__ . '/db/meshsilo.db');

PHPEOF
    fi

    # Site configuration
    cat >> "$CONFIG_FILE" << PHPEOF
// Site Configuration
define('SITE_NAME', '${MESHSILO_SITE_NAME:-MeshSilo}');
define('SITE_DESCRIPTION', '${MESHSILO_SITE_DESCRIPTION:-3D Print File Manager}');
define('SITE_URL', '${MESHSILO_SITE_URL:-}');

PHPEOF

    # OIDC configuration if enabled
    if [ -n "$MESHSILO_OIDC_PROVIDER_URL" ]; then
        cat >> "$CONFIG_FILE" << PHPEOF
// OIDC Configuration
define('OIDC_ENABLED', true);
define('OIDC_PROVIDER_URL', '${MESHSILO_OIDC_PROVIDER_URL}');
define('OIDC_CLIENT_ID', '${MESHSILO_OIDC_CLIENT_ID:-}');
define('OIDC_CLIENT_SECRET', '${MESHSILO_OIDC_CLIENT_SECRET:-}');
define('OIDC_REDIRECT_URI', '${MESHSILO_OIDC_REDIRECT_URI:-}');
define('OIDC_SCOPES', '${MESHSILO_OIDC_SCOPES:-openid profile email}');
define('OIDC_USERNAME_CLAIM', '${MESHSILO_OIDC_USERNAME_CLAIM:-preferred_username}');
define('OIDC_DISPLAY_NAME_CLAIM', '${MESHSILO_OIDC_DISPLAY_NAME_CLAIM:-name}');
define('OIDC_EMAIL_CLAIM', '${MESHSILO_OIDC_EMAIL_CLAIM:-email}');
define('OIDC_AUTO_REGISTER', ${MESHSILO_OIDC_AUTO_REGISTER:-true});
define('OIDC_DEFAULT_GROUP', '${MESHSILO_OIDC_DEFAULT_GROUP:-}');

PHPEOF
    else
        cat >> "$CONFIG_FILE" << 'PHPEOF'
// OIDC Configuration (disabled)
define('OIDC_ENABLED', false);

PHPEOF
    fi

    # Settings
    cat >> "$CONFIG_FILE" << PHPEOF
// Application Settings
define('ALLOWED_EXTENSIONS', '${MESHSILO_ALLOWED_EXTENSIONS:-stl,3mf,obj,ply,amf,gcode,glb,gltf,fbx,dae,blend,step,stp,iges,igs,3ds,dxf,off,x3d}');
define('MAX_UPLOAD_SIZE', '${MESHSILO_MAX_UPLOAD_SIZE:-104857600}');
define('DEDUP_ENABLED', ${MESHSILO_DEDUP_ENABLED:-true});

PHPEOF

    chown www-data:www-data "$CONFIG_FILE"
    chmod 640 "$CONFIG_FILE"

    echo "Configuration file created at $CONFIG_FILE"
fi

# If using SQLite and auto-setup is enabled, initialize the database
if [ "$MESHSILO_AUTO_SETUP" = "true" ] && [ -f "$CONFIG_FILE" ]; then
    # Check if database exists
    if [ "$MESHSILO_DB_TYPE" != "mysql" ] && [ ! -f "/var/www/meshsilo/db/meshsilo.db" ]; then
        echo "Auto-setup enabled but database not found."
        echo "Please visit the installation wizard at /install.php to complete setup."
    fi
fi

# Update PHP upload limits from environment if specified
if [ -n "$MESHSILO_MAX_UPLOAD_SIZE" ]; then
    # Convert to MB for PHP config
    UPLOAD_MB=$(($MESHSILO_MAX_UPLOAD_SIZE / 1048576))

    # Update the custom config file to override defaults
    sed -i "s/^upload_max_filesize = .*/upload_max_filesize = ${UPLOAD_MB}M/" /etc/php/8.1/fpm/conf.d/99-meshsilo.ini
    sed -i "s/^post_max_size = .*/post_max_size = ${UPLOAD_MB}M/" /etc/php/8.1/fpm/conf.d/99-meshsilo.ini

    # Update nginx client_max_body_size
    sed -i "s/client_max_body_size .*/client_max_body_size ${UPLOAD_MB}M;/" /etc/nginx/sites-available/default
fi

echo "MeshSilo Docker container starting..."
echo "Access the application at http://localhost:80"

# Execute the main command
exec "$@"
